### ISSUE TITLE
themes fail to import when loading

### ISSUE THREAD

**Issue by Panniku** [Gabe616/VendettaCloudSync#10]
to replicate, have a theme above other themes which is invalid / cant be fetched
then, save data and load.

Expected:
all themes load

Result:
every theme except the invalid theme and the other themes after it fail to load

**Comment by Gabe616** [comment]
could you create an issue in https://github.com/Gabe616/VendettaPlugins instead, this is for the backend

**Comment by Panniku** [comment]
sure
